version: 1
duckdb:
  database: catalog.duckdb
views:
  - name: active_users
    description: "Users who are currently active"
    sql_file:
      path: "sql/active_users.sql"

  - name: recent_orders
    description: "Orders from the last 30 days"
    sql_template:
      path: "sql/recent_orders_template.sql"
      variables:
        days_back: 30

  - name: top_customers
    description: "Top customers by revenue"
    sql: |
      SELECT 
        customer_id,
        SUM(amount) as total_revenue,
        COUNT(*) as order_count
      FROM orders
      GROUP BY customer_id
      ORDER BY total_revenue DESC
      LIMIT 100