version: 1

duckdb:
  database: "performance_limited.duckdb"
  install_extensions:
    - parquet
  pragmas:
    # Conservative Memory Usage - For systems with 4GB RAM or less
    - "SET memory_limit='1GB'"
    - "SET max_memory='1GB'"

    # Limited Parallelism - For single/dual-core systems
    - "SET threads=2"
    - "SET enable_progress_bar=true"

    # Efficient Storage
    - "SET temp_directory='./temp'"
    - "SET preserve_insertion_order=false"

# Resource-conscious views for limited environments
views:
  - name: events_small
    source: parquet
    uri: "datasets/events_small.parquet"
    description: "Small dataset (100K rows) for limited resources"

  
  - name: lightweight_analytics
    sql: |
      SELECT
        event_type,
        COUNT(*) as event_count,
        COUNT(DISTINCT user_id) as unique_users,
        MIN(timestamp) as first_event,
        MAX(timestamp) as last_event
      FROM events_small
      GROUP BY event_type
      ORDER BY event_count DESC
    description: "Lightweight aggregation for limited resources"

  - name: daily_summary_efficient
    sql: |
      SELECT
        DATE(timestamp) as event_date,
        COUNT(*) as daily_events,
        COUNT(DISTINCT user_id) as daily_users
      FROM events_small
      WHERE timestamp >= CURRENT_DATE - INTERVAL '30 days'
      GROUP BY DATE(timestamp)
      ORDER BY event_date DESC
      LIMIT 100
    description: "Memory-efficient daily summary"

  - name: user_activity_light
    sql: |
      SELECT
        user_id,
        COUNT(*) as total_events,
        MIN(timestamp) as first_seen,
        MAX(timestamp) as last_seen
      FROM events_small
      WHERE user_id IS NOT NULL
      GROUP BY user_id
      HAVING COUNT(*) > 5  -- Only include users with sufficient activity
      ORDER BY total_events DESC
      LIMIT 1000  -- Limit result size
    description: "Lightweight user activity analysis"

  - name: limited_performance_validation
    sql: |
      SELECT
        'performance_limited' as configuration,
        CURRENT_TIMESTAMP as validation_timestamp,
        (SELECT COUNT(*) FROM events_small) as available_rows,
        (SELECT COUNT(DISTINCT event_type) FROM events_small) as unique_event_types,
        (SELECT COUNT(DISTINCT user_id) FROM events_small) as unique_users,
        (SELECT DATE_PART('day', MAX(timestamp) - MIN(timestamp)) FROM events_small) as data_span_days
    description: "Limited configuration performance validation"