version: 1

duckdb:
  database: multi_source_analytics.duckdb
  install_extensions:
    - httpfs
    - json
  pragmas:
    - "SET memory_limit='2GB'"
    - "SET threads=4"
    - "SET timezone='UTC'"

attachments:
  duckdb:
    - alias: reference
      path: ./data/reference_data.duckdb
      read_only: true

views:
  # Raw data from different sources
  - name: raw_events
    source: parquet
    uri: ./data/events/*.parquet
    description: "Raw events from data lake simulation"

  - name: user_profiles
    source: duckdb
    database: reference
    table: users
    description: "User reference data"

  - name: product_data
    source: duckdb
    database: reference
    table: products
    description: "Product reference data"

  # Enriched analytics views
  - name: enriched_events
    sql: |
      SELECT
        e.event_id,
        e.timestamp,
        e.event_type,
        e.user_id,
        e.session_id,
        e.properties,
        u.name as user_name,
        u.email as user_email,
        u.segment as user_segment,
        p.name as product_name,
        p.category as product_category
      FROM raw_events e
      LEFT JOIN user_profiles u ON e.user_id = u.id
      LEFT JOIN product_data p ON e.properties->>'product_id' = p.id
    description: "Events enriched with user and product data"

  # Analytics metrics
  - name: event_metrics
    sql: |
      SELECT
        DATE(timestamp) as event_date,
        event_type,
        COUNT(*) as event_count,
        COUNT(DISTINCT user_id) as unique_users,
        COUNT(DISTINCT session_id) as unique_sessions
      FROM enriched_events
      GROUP BY DATE(timestamp), event_type
      ORDER BY event_date DESC, event_count DESC
    description: "Daily event metrics for reporting"

  - name: user_activity_summary
    sql: |
      SELECT
        u.id as user_id,
        u.name,
        u.email,
        u.segment,
        COUNT(DISTINCT DATE(ee.timestamp)) as active_days,
        COUNT(DISTINCT ee.session_id) as total_sessions,
        COUNT(*) as total_events,
        MAX(ee.timestamp) as last_activity
      FROM user_profiles u
      LEFT JOIN enriched_events ee ON u.id = ee.user_id
      GROUP BY u.id, u.name, u.email, u.segment
      ORDER BY total_events DESC
    description: "User engagement summary"

  - name: product_performance
    sql: |
      SELECT
        p.id as product_id,
        p.name as product_name,
        p.category,
        COUNT(*) as event_count,
        COUNT(DISTINCT ee.user_id) as unique_users,
        MAX(ee.timestamp) as last_mentioned
      FROM product_data p
      JOIN enriched_events ee ON p.id = ee.properties->>'product_id'
      GROUP BY p.id, p.name, p.category
      ORDER BY event_count DESC
    description: "Product engagement analysis"

  # Executive KPI reporting
  - name: daily_kpi_report
    sql: |
      WITH daily_metrics AS (
        SELECT
          DATE(timestamp) as event_date,
          COUNT(*) as total_events,
          COUNT(DISTINCT user_id) as daily_active_users,
          COUNT(DISTINCT session_id) as daily_sessions
        FROM enriched_events
        GROUP BY DATE(timestamp)
      )
      SELECT
        event_date,
        total_events,
        daily_active_users,
        daily_sessions,
        ROUND(total_events * 1.0 / daily_sessions, 2) as events_per_session,
        LAG(daily_active_users) OVER (ORDER BY event_date) as prev_day_users,
        ROUND((daily_active_users - LAG(daily_active_users) OVER (ORDER BY event_date)) * 100.0 /
              NULLIF(LAG(daily_active_users) OVER (ORDER BY event_date), 0), 2) as user_growth_pct
      FROM daily_metrics
      ORDER BY event_date DESC
    description: "Executive KPI dashboard data"
