# Multi-Source Joins - Duckalog Configuration
# This example shows joining data from multiple sources

duckdb:
  database: catalog.duckdb

views:
  - name: users
    source: parquet
    uri: "data/users.parquet"

  - name: events
    source: parquet
    uri: "data/events.parquet"

attachments:
  duckdb:
    - alias: reference
      path: "data/reference.duckdb"
      read_only: true

  - name: enriched_events
    sql: |
      SELECT
        e.event_id,
        e.user_id,
        e.event_type,
        e.event_timestamp,
        u.name AS user_name,
        u.email AS user_email,
        u.country AS user_country,
        u.is_active AS user_is_active,
        p.bio AS profile_bio,
        p.avatar_url AS profile_avatar
      FROM events e
      JOIN users u ON e.user_id = u.id
      LEFT JOIN reference.profiles p ON e.user_id = p.id
      ORDER BY e.event_timestamp DESC
