# CSV Basics - Duckalog Configuration
# This example shows how to configure CSV file sources

version: 1

duckdb:
  database: catalog.duckdb

views:
  - name: customers
    sql: |
      SELECT * FROM read_csv_auto('data/customers.csv')
    description: "Customer data from CSV file"
