# Hierarchical Configuration with Database Path Override

This example demonstrates how parent configs can override the database paths of child configs, allowing for custom organization of built databases.

## child.yaml - Standard Child Configuration
```yaml
# Child config that would normally build to its own directory
version: 1
duckdb:
  database: child.duckdb  # Default database location

views:
  - name: sales_data
    sql: |
      SELECT
        1 AS sale_id,
        'Product A' AS product_name,
        100.0 AS revenue,
        '2024-01-01' AS sale_date
      UNION ALL
      SELECT
        2 AS sale_id,
        'Product B' AS product_name,
        150.0 AS revenue,
        '2024-01-02' AS sale_date

  - name: customer_data
    sql: |
      SELECT
        1 AS customer_id,
        'Customer X' AS customer_name,
        'premium' AS segment
      UNION ALL
      SELECT
        2 AS customer_id,
        'Customer Y' AS customer_name,
        'standard' AS segment
```

## parent.yaml - Parent with Database Override
```yaml
# Parent config that overrides child's database location
version: 1
duckdb:
  database: main.duckdb

attachments:
  duckalog:
    - alias: sales_db
      config_path: ./child.yaml
      database: ./databases/child_catalog.duckdb  # Override child's database path
      read_only: true
    - alias: analytics_db
      config_path: ./child.yaml
      database: ./databases/analytics_child.duckdb  # Different alias, same config, different location
      read_only: true

views:
  - name: sales_summary
    sql: |
      SELECT
        'Total Sales' AS metric,
        COUNT(*) AS count,
        SUM(revenue) AS total_revenue,
        AVG(revenue) AS avg_revenue
      FROM sales_db.sales_data

  - name: customer_insights
    sql: |
      SELECT
        segment,
        COUNT(*) AS customer_count,
        STRING_AGG(customer_name, ', ') AS customers
      FROM analytics_db.customer_data
      GROUP BY segment

  - name: cross_database_metrics
    sql: |
      -- Combine data from both instances of the same child config
      SELECT
        'Sales Database' AS source,
        (SELECT COUNT(*) FROM sales_db.sales_data) AS record_count
      UNION ALL
      SELECT
        'Analytics Database' AS source,
        (SELECT COUNT(*) FROM analytics_db.customer_data) AS record_count
```

## Directory Structure After Build

```
project/
├── child.yaml
├── parent.yaml
├── main.duckdb              # Main parent database
└── databases/               # Custom directory created for child databases
    ├── child_catalog.duckdb     # First instance of child config
    └── analytics_child.duckdb   # Second instance of child config
```

## Usage

Build the catalog with database overrides:

```bash
duckalog build parent.yaml
```

## What Happens During Build

1. **First Attachment (`sales_db`)**:
   - Loads `child.yaml`
   - Overrides database path from `child.duckdb` to `./databases/child_catalog.duckdb`
   - Creates the `./databases/` directory if it doesn't exist
   - Builds the child database at the custom location
   - Attaches it to parent as `sales_db`

2. **Second Attachment (`analytics_db`)**:
   - Loads the same `child.yaml` configuration
   - Overrides database path to `./databases/analytics_child.duckdb`
   - Builds another instance of the child database (same structure, different location)
   - Attaches it to parent as `analytics_db`

3. **Parent Views**:
   - Created in `main.duckdb`
   - Reference data from both attached child databases
   - Use different aliases to distinguish between the two instances

## Benefits of Database Override

1. **Custom Organization**: Place child databases in dedicated directories
2. **Multiple Instances**: Use the same child config in different contexts
3. **Path Management**: Override relative paths to fit project structure
4. **Naming Control**: Use descriptive names for child database files
5. **Environment Separation**: Different overrides for dev/staging/prod

## Advanced Override Example

You can also combine database override with relative path resolution:

```yaml
attachments:
  duckalog:
    - alias: shared_ref
      config_path: ../shared/reference.yaml  # Reference config in parent directory
      database: ../data/reference.duckdb      # Custom location outside project
      read_only: true
```

This allows for flexible project organization while maintaining clean configuration files.