version: 1

duckdb:
  database: analytics_catalog.duckdb

  pragmas:
    - "SET memory_limit='2GB'"

views:
  # Raw data views
  - name: raw_users
    source: parquet
    uri: "./data/users.parquet" # Supports partitioned data
    description: "User data from partitioned Parquet files"

  - name: raw_events
    source: parquet
    uri: "data/events.parquet"
    description: "Event data from partitioned Parquet files"

  # Derived views with analytics
  - name: daily_active_users
    sql: |
      SELECT
        DATE(timestamp) as event_date,
        COUNT(DISTINCT user_id) as active_users,
        COUNT(*) as total_events
      FROM raw_events
      GROUP BY DATE(timestamp)
      ORDER BY event_date DESC
    description: "Daily active user metrics"

  - name: user_summary
    sql: |
      SELECT
        u.user_id,
        u.name,
        u.region,
        u.signup_date,
        COUNT(DISTINCT DATE(e.timestamp)) as active_days,
        COUNT(e.event_id) as total_events,
        MAX(e.timestamp) as last_activity
      FROM raw_users u
      LEFT JOIN raw_events e ON u.user_id = e.user_id
      GROUP BY u.user_id, u.name, u.region, u.signup_date
      ORDER BY total_events DESC NULLS LAST
    description: "User engagement summary"

  - name: popular_content
    sql: |
      SELECT
        event_type,
        COUNT(*) as event_count,
        COUNT(DISTINCT user_id) as unique_users,
        AVG(value) as avg_value
      FROM raw_events
      WHERE event_type IN ('page_view', 'click', 'purchase')
      GROUP BY event_type
      ORDER BY event_count DESC
    description: "Most popular content types"
