# SQL Transformations - Duckalog Configuration
# This example shows inline SQL and external SQL file references

duckdb:
  database: catalog.duckdb

views:
  - name: users
    source: parquet
    uri: "data/users.parquet"

  - name: events
    source: parquet
    uri: "data/events.parquet"

  - name: daily_metrics
    sql: |
      WITH daily_stats AS (
        SELECT
          DATE_TRUNC('day', event_timestamp) AS event_date,
          event_type,
          COUNT(*) AS event_count,
          COUNT(DISTINCT user_id) AS unique_users
        FROM events
        GROUP BY DATE_TRUNC('day', event_timestamp), event_type
      )
      SELECT
        event_date,
        event_type,
        event_count,
        unique_users,
        ROUND(event_count::DOUBLE / unique_users, 2) AS events_per_user
      FROM daily_stats
      ORDER BY event_date DESC, event_count DESC

  - name: user_summary
    sql_file: "sql/user_summary.sql"
